const express = require('express')
const teacher = require('./routes/teacher')
const student = require('./routes/student')
const subject = require('./routes/subject')
const user = require('./routes/user')
const app = express()
app.set('view engine', 'ejs')
app.use(express.urlencoded({extended:false}))
app.get('/', function(req, res) {
  res.render('home-school')
})
app.use('/teachers', teacher)
app.use('/students', student)
app.use('/subjects', subject)
app.use('/user', user)
app.listen(3000, function() {
  console.log('this is port 3000...')
})